
# Exported from Render on 2024-06-19T09:26:59Z
databases:
  - name: taskman
    databaseName: taskman_prwu
    user: taskman
    plan: free
    region: oregon
    ipAllowList:
    - source: 0.0.0.0/0
      description: everywhere
    postgresMajorVersion: "16"
  version: "1"


services:
  - type: web
    name: taskman
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskman
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
